### ISSUE TITLE
Bug: SensorDataQuery

### ISSUE THREAD

**Issue by trevorki** [AretasSensorNetworks/AretasPythonAPI#1]
**Describe the bug**
When calling `SensorDataQuery.get_data()` with the `types` argument, all types are returned, not just the one requested

**To Reproduce**
```
config = APIConfig()       
sdq = SensorDataQuery(auth) 
response = sdq.get_data(
    mac=13762505, 
    begin=1692100000000, 
    end = 1692140000000, 
    types=[181])
print(response[0:12])
```

**Expected behavior**
[{'mac': 13762505, 'type': 181, 'timestamp': 1692100047304, 'data': 462.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100107448, 'data': 462.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100167586, 'data': 463.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100227541, 'data': 463.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100287372, 'data': 463.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100347624, 'data': 462.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100407389, 'data': 462.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100467392, 'data': 463.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100527843, 'data': 463.0},
{'mac': 13762505, 'type': 181, 'timestamp': 1692100602686, 'data': 463.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100648506, 'data': 464.0},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100710874, 'data': 464.0}]

**Actual Behaviour**
[{'mac': 13762505, 'type': 246, 'timestamp': 1692100026957, 'data': 29.65},
 {'mac': 13762505, 'type': 242, 'timestamp': 1692100029009, 'data': 85.38},
 {'mac': 13762505, 'type': 32, 'timestamp': 1692100031080, 'data': 0.0},
 {'mac': 13762505, 'type': 33, 'timestamp': 1692100033103, 'data': 0.0},
 {'mac': 13762505, 'type': 34, 'timestamp': 1692100035107, 'data': 0.0},
 {'mac': 13762505, 'type': 182, 'timestamp': 1692100037150, 'data': 728.0},
 {'mac': 13762505, 'type': 96, 'timestamp': 1692100039164, 'data': 229.0},
 {'mac': 13762505, 'type': 28, 'timestamp': 1692100041211, 'data': 3.0},
 {'mac': 13762505, 'type': 50, 'timestamp': 1692100043226, 'data': 56.87},
 {'mac': 13762505, 'type': 49, 'timestamp': 1692100045276, 'data': 56.36},
 {'mac': 13762505, 'type': 181, 'timestamp': 1692100047304, 'data': 462.0},
 {'mac': 13762505, 'type': 115, 'timestamp': 1692100049302, 'data': 2.33}]

**Comment by ElDuderino** [comment]
Hi Trevor! Thanks for noticing this and filing the issue. Ironically, this was fixed a couple of days ago in commit 6b38d76 

There is some ambiguity with how the API handles multiple type filtering (the GET query URL ends up looking like: ```type=96&type=181&type=245``` etc.) vs the naming for the list of the argument: ```types=``` 

Anyway, it's fixed now :)
